graph LR;
 diameter([Diameter - TCP/SCTP])-->ingress[BIG-IP NEXT];
 client([SIP - TCP/UDP])-->ingress[BIG-IP NEXT];
 http([HTTP/2 - TCP])-->ingress[BIG-IP NEXT];
 ingress-->service[Service];
 subgraph K8S CLUSTER
  service-->pod1[Pod];
  service-->pod2[Pod];
 end
 subgraph SERVICE PROXY
  ingress;
 end
